name: release-and-publish

on:
  push:
    branches:
      - main

  # Allows workflow to be run manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  id-token: write # Required for OIDC when publishing to npm
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42
        id: app-token
        with:
          app-id: ${{ vars.CI_RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.CI_RELEASE_BOT_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}
          release-type: node

      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install pnpm
        if: ${{ steps.release.outputs.release_created }}
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm i --frozen-lockfile

      - name: Build package
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm build

      - name: Publish
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm publish --access public
